server.port: 8888
eureka:
  instance:
    hostname: localhost
  dashboard.path: /registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/